### PR TITLE
Handle Clipboard being undefined in insecure contexts

### LINKED ISSUE #14: Types don't reflect that clipboard is undefined in insecure contexts
The referenced w3 API specifies:

```
partial interface [Navigator](https://html.spec.whatwg.org/multipage/system-state.html#navigator) {
  [[SecureContext](https://webidl.spec.whatwg.org/#SecureContext), [SameObject](https://webidl.spec.whatwg.org/#SameObject)] readonly attribute [Clipboard](https://www.w3.org/TR/clipboard-apis/#clipboard) [clipboard](https://www.w3.org/TR/clipboard-apis/#dom-navigator-clipboard);
};
```

and sure enough, on insecure pages (with `window.isSecureContext === false`) like about:blank (or any other HTTP pages), `window.clipboard` is undefined.

For me, this meant that calling writeText caused my Effect computation to abort (with no error!) See screenshot:

image

I am not sure what the right way to address this should be. Should `clipboard` have type `Window -> Maybe Clipboard` instead? Internally, it could check for `undefined`. That might be more robust than checking `isSecureContext`.

### PR DESCRIPTION
**Pull request by ysangkok**
Fixes #14.

### CODE REVIEW

**Comment by ysangkok** [comment]
I tested this with the following program:

```
module Test.Main where

import Prelude
import Effect (Effect)
import Effect.Console (log)
import Web.Clipboard (clipboard)
import Data.Maybe (isJust)
import Web.HTML (window)
import Web.HTML.Window (navigator)

main :: Effect Unit
main = do
  clp <- window >>= navigator >>= clipboard
  log $ show $ isJust $ clp
```

Which I bundled using

`spago bundle --platform browser --bundle-type app --module Test.Main --outfile index.js`

**Comment by garyb** [comment]
Would you mind making one further change? Add an explicit export list that exports everything aside from the `clipboardWrapper`. Thanks!

**Comment by ysangkok** [comment]
@garyb Done

**Comment by garyb** [comment]
Sorry, one last minor thing, `eslint` is complaining because of single rather than double quotes (`'undefined'`) in the JS.

**Comment by ysangkok** [comment]
@garyb Added a commit to switch quote style, tested with following `eslint.config.mjs` configuration:

```
import globals from "globals";
import pluginJs from "@eslint/js";
import stylisticJs from "@stylistic/eslint-plugin-js"

export default [
  {
    languageOptions: { globals: globals.browser }
    , plugins: {"@stylistic/js": stylisticJs}
    , rules:
        {
          "@stylistic/js/indent": ["warn", 2]
          , "@stylistic/js/quotes": ["warn", "double"]
        }
  },
  pluginJs.configs.recommended,
];
```

**Comment by garyb** [comment]
Thanks!

**Pull request merged**
